### ISSUE TITLE
Error with iOS8

### ISSUE THREAD

**Issue by fabnoe** [angelolloqui/AGBlurTransition#4]
xCode throws an error at Line 122:

    [parent addSubview:self.backgroundView];

exception 'NSInvalidArgumentException', reason: 'Can't add self as subview'

**Comment by xiaoxu193** [comment]
Also got ``'Can't add self as subview'``. Fix coming soon?

**Comment by angelolloqui** [comment]
Sorry guys, new 0.0.2 version pushed.
